<a href="https://colab.research.google.com/github/LucilleKaleha/W4_Python_Notebook/blob/master/Moringa_Data_Science_Prep_W4_Independent_Project_2019_07_Lucille_Kaleha_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Week 4 Independent Project: Processing Data for Stations to understand Electric Car Usage Over Time

# 1.0 Importing Libraries

In [0]:
import pandas as pd

# 1.1 Reading and Previewing our Dataset fro the CSV File

In [0]:
url = 'http://bit.ly/Autolibdataset'
Autolib = pd.read_csv(url)
Autolib.head()

   Unnamed: 0                     Address  Cars  ...  day  hour  minute
0           0              24 Rue Vulpian     3  ...    1     0       0
1           1  8 Boulevard Richard Lenoir     0  ...    1     0       0
2           2        4 Rue Charles Bossut     3  ...    1     0       0
3           3   3 avenue Claude Vellefaux     4  ...    1     0       0
4           4      236 Boulevard Voltaire     1  ...    1     0       0

[5 rows x 26 columns]

# 1.2 Getting Information about our Dataset

In [0]:
# Knowing more about the dataset by accessing its information
Autolib.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14421829 entries, 0 to 14421828
Data columns (total 26 columns):
Unnamed: 0             int64
Address                object
Cars                   int64
Bluecar counter        int64
Utilib counter         int64
Utilib 1.4 counter     int64
Charge Slots           int64
Charging Status        object
City                   object
Displayed comment      object
ID                     object
Kind                   object
Geo point              object
Postal code            int64
Public name            object
Rental status          object
Scheduled at           object
Slots                  int64
Station type           object
Status                 object
Subscription status    object
year                   int64
month                  int64
day                    int64
hour                   int64
minute                 int64
dtypes: int64(13), object(13)
memory usage: 2.8+ GB

In [0]:
# Checking for null values
Autolib.isnull().any()

Unnamed: 0             False
Address                False
Cars                   False
Bluecar counter        False
Utilib counter         False
Utilib 1.4 counter     False
Charge Slots           False
Charging Status        False
City                   False
Displayed comment       True
ID                     False
Kind                   False
Geo point              False
Postal code            False
Public name            False
Rental status          False
Scheduled at            True
Slots                  False
Station type           False
Status                 False
Subscription status    False
year                   False
month                  False
day                    False
hour                   False
minute                 False
dtype: bool

In [0]:
# Checking for missing values
Autolib.count()
rows = Autolib.shape[0]
missing = rows - Autolib.count()
missing

Unnamed: 0                    0
Address                       0
Cars                          0
Bluecar counter               0
Utilib counter                0
Utilib 1.4 counter            0
Charge Slots                  0
Charging Status               0
City                          0
Displayed comment      14099610
ID                            0
Kind                          0
Geo point                     0
Postal code                   0
Public name                   0
Rental status                 0
Scheduled at           14310213
Slots                         0
Station type                  0
Status                        0
Subscription status           0
year                          0
month                         0
day                           0
hour                          0
minute                        0
dtype: int64

#1.3 Cleaning the Dataset

In [0]:
# Checking for Outliers
Q1 = Autolib.quantile(0.25)
Q3 = Autolib.quantile(0.75)

IQR = Q3 - Q1 

(Autolib < (Q1 - 1.5 * IQR)) |(Autolib > (Q3 + 1.5 * IQR))
# Will not drop any outliers

          Address  Bluecar counter   Cars  ...  minute  month   year
0           False            False  False  ...   False  False  False
1           False            False  False  ...   False  False  False
2           False            False  False  ...   False  False  False
3           False            False  False  ...   False  False  False
4           False            False  False  ...   False  False  False
5           False            False  False  ...   False  False  False
6           False            False  False  ...   False  False  False
7           False            False  False  ...   False  False  False
8           False            False  False  ...   False  False  False
9           False            False  False  ...   False  False  False
10          False            False  False  ...   False  False  False
11          False            False  False  ...   False  False  False
12          False            False  False  ...   False  False  False
13          False            False  False  ...   False  False  False
14          False            False  False  ...   False  False  False
15          False            False  False  ...   False  False  False
16          False            False  False  ...   False  False  False
17          False            False  False  ...   False  False  False
18          False            False  False  ...   False  False  False
19          False            False  False  ...   False  False  False
20          False            False  False  ...   False  False  False
21          False            False  False  ...   False  False  False
22          False            False  False  ...   False  False  False
23          False            False  False  ...   False  False  False
24          False            False  False  ...   False  False  False
25          False            False  False  ...   False  False  False
26          False            False  False  ...   False  False  False
27          False            False  False  ...   False  False  False
28          False            False  False  ...   False  False  False
29          False            False  False  ...   False  False  False
...           ...              ...    ...  ...     ...    ...    ...
14421799    False            False  False  ...   False  False  False
14421800    False            False  False  ...   False  False  False
14421801    False            False  False  ...   False  False  False
14421802    False            False  False  ...   False  False  False
14421803    False            False  False  ...   False  False  False
14421804    False            False  False  ...   False  False  False
14421805    False            False  False  ...   False  False  False
14421806    False            False  False  ...   False  False  False
14421807    False            False  False  ...   False  False  False
14421808    False            False  False  ...   False  False  False
14421809    False            False  False  ...   False  False  False
14421810    False            False  False  ...   False  False  False
14421811    False            False  False  ...   False  False  False
14421812    False            False  False  ...   False  False  False
14421813    False            False  False  ...   False  False  False
14421814    False            False  False  ...   False  False  False
14421815    False            False  False  ...   False  False  False
14421816    False            False  False  ...   False  False  False
14421817    False            False  False  ...   False  False  False
14421818    False            False  False  ...   False  False  False
14421819    False            False  False  ...   False  False  False
14421820    False            False  False  ...   False  False  False
14421821    False            False  False  ...   False  False  False
14421822    False            False  False  ...   False  False  False
14421823    False            False  False  ...   False  False  False
14421824    False            False  False  ...   False  False  False
14421825    False            False  False  ...   False  False  False
14421826    False            False  False  ...   False  False  False
14421827    False            False  False  ...   False  False  False
14421828    False            False  False  ...   False  False  False

[14421829 rows x 26 columns]

In [0]:
# Deleting Irrelevant Columns
Autolib.drop(['Unnamed: 0', 'Address','Cars', 'Charge Slots', 'ID', 'Geo point','Displayed comment',
             'Scheduled at', 'year', 'month'], axis = 1, inplace = True)
Autolib

          Bluecar counter  Utilib counter  ...  hour minute
0                       3               1  ...     0      0
1                       0               0  ...     0      0
2                       3               0  ...     0      0
3                       4               0  ...     0      0
4                       1               0  ...     0      0
5                       1               0  ...     0      0
6                       1               0  ...     0      0
7                       0               0  ...     0      0
8                       4               0  ...     0      0
9                       2               0  ...     0      0
10                      3               0  ...     0      0
11                      2               0  ...     0      0
12                      0               0  ...     0      0
13                      4               0  ...     0      0
14                      1               0  ...     0      0
15                      1               1  ...     0      0
16                      0               0  ...     0      0
17                      1               0  ...     0      0
18                      1               1  ...     0      0
19                      1               0  ...     0      0
20                      1               0  ...     0      0
21                      5               0  ...     0      0
22                      0               0  ...     0      0
23                      0               0  ...     0      0
24                      2               0  ...     0      0
25                      2               0  ...     0      0
26                      2               0  ...     0      0
27                      3               0  ...     0      0
28                      0               0  ...     0      0
29                      1               0  ...     0      0
...                   ...             ...  ...   ...    ...
14421799                0               0  ...    23     59
14421800                3               1  ...    23     59
14421801                3               0  ...    23     59
14421802                3               0  ...    23     59
14421803                7               0  ...    23     59
14421804                3               0  ...    23     59
14421805                2               0  ...    23     59
14421806                0               0  ...    23     59
14421807                5               0  ...    23     59
14421808                5               0  ...    23     59
14421809                0               0  ...    23     59
14421810                0               0  ...    23     59
14421811                4               0  ...    23     59
14421812                6               0  ...    23     59
14421813                2               0  ...    23     59
14421814                0               0  ...    23     59
14421815                5               0  ...    23     59
14421816                3               0  ...    23     59
14421817                3               0  ...    23     59
14421818                5               0  ...    23     59
14421819                0               0  ...    23     59
14421820                0               0  ...    23     59
14421821                0               0  ...    23     59
14421822                0               0  ...    23     59
14421823                5               0  ...    23     59
14421824                2               0  ...    23     59
14421825                3               0  ...    23     59
14421826                5               0  ...    23     59
14421827                0               0  ...    23     59
14421828                1               0  ...    23     59

[14421829 rows x 16 columns]

In [0]:
# Removing Special Characters from columns
Autolib['Public name'] = Autolib['Public name'].str.replace("/", " ")

In [0]:
# Dropping the duplicate values in our dataset
Autolib.drop_duplicates()
Autolib.head()

   Bluecar counter  Utilib counter  Utilib 1.4 counter  ... day hour minute
0                3               1                   0  ...   1    0      0
1                0               0                   0  ...   1    0      0
2                3               0                   0  ...   1    0      0
3                4               0                   0  ...   1    0      0
4                1               0                   0  ...   1    0      0

[5 rows x 16 columns]

In [0]:
# Creating new columns with counter difference
Autolib['Bluecar counter difference'] = Autolib['Bluecar counter'].diff()
Autolib['Utilib counter difference'] = Autolib['Utilib counter'].diff()
Autolib['Utilib 1.4 counter difference'] = Autolib['Utilib 1.4 counter'].diff()
Autolib.head()
# A negative value in the counter difference means a car was picked from the station and a positive value means
# a car was returned

   Bluecar counter  ...  Utilib 1.4 counter difference
0                3  ...                            NaN
1                0  ...                            0.0
2                3  ...                            0.0
3                4  ...                            0.0
4                1  ...                            0.0

[5 rows x 19 columns]

In [0]:
Autolib.columns = ['Bluecar_counter',	'Utilib_counter',	'Utilib_1.4_counter',	'Charging_status', 'City',	'Kind',
        'Postal_code',	'Public_name',	'Rental_status', 'Slots',	'Station_type',	'Status',	'Subscription_status',
        'day',	'hour',	'minute',	'Bluecar_counter_difference', 'Utilib_counter_difference',	'Utilib1.4_counter_difference']
Autolib.head()

   Bluecar_counter  ...  Utilib1.4_counter_difference
0                3  ...                           NaN
1                0  ...                           0.0
2                3  ...                           0.0
3                4  ...                           0.0
4                1  ...                           0.0

[5 rows x 19 columns]

# 1.4 Answering Questions

Questions Relating to Bluecar Counter

In [0]:
# Research Question
# Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris 
# over the month of April 2018

Autolib[(Autolib.City == 'Paris') & (Autolib.Bluecar_counter_difference < 0)].groupby('hour')['hour'].count().sort_values(ascending = False).head(10)

hour
4     149876
3     149726
7     149379
2     149266
6     149131
5     148976
8     148571
9     148510
10    148394
14    147197
Name: hour, dtype: int64

In [0]:
# Bonus Question 1
# What is the most popular hour for returning cars?

Autolib[Autolib.Bluecar_counter_difference > 0].groupby('hour')['hour'].count().sort_values(ascending = False).head(10)

hour
21    252085
10    251225
7     250521
5     250389
6     250265
8     250075
4     249864
9     249670
2     249547
3     248282
Name: hour, dtype: int64

In [0]:
# Bonus Question 2.1
# What station is the most popular?
# Overall?
Autolib[(Autolib.Kind == 'STATION') & (Autolib.Status == 'ok')].groupby('Public_name')['Public_name'].count().sort_values(ascending= False).head(10)

Public_name
Paris UzÃ¨s 1                        12927
Paris Sibelle 29                     12922
Paris Ramey 62                       12920
Bagnolet Pasteur 124                 12918
Paris Maine 185                      12917
Paris Dante 1                        12915
Aulnay-sous-bois Maryse BastiÃ© 1    12915
Montreuil GalilÃ©e 29                12914
Paris Louis Blanc 6                  12914
Colombes Seine 52                    12914
Name: Public_name, dtype: int64

In [0]:
# Bonus Question 2.2
# What station is the most popular?
# At the most popular picking hour?
Autolib[(Autolib.Kind == 'STATION') & (Autolib.Status == 'ok') & (Autolib.hour == 4)].groupby('Public_name')['Public_name'].count().sort_values(ascending= False).head(10)

Public_name
Paris Bosquet 41                             554
Paris Manin 159                              553
Paris Grange aux Belles 11                   553
Paris Mademoiselle 22                        553
Le Plessis-Robinson Aristide Briand 51       553
Drancy Roger Salengro 97                     553
Paris Raymond PoincarÃ© 51                   553
SÃ¨vres Riocreux 1                           552
Paris Artois 11                              552
Boulogne-Billancourt Alphonse Le Gallo 35    552
Name: Public_name, dtype: int64

In [0]:
# Bonus Question 3.1
# What postal code is the most popular for picking up Bluecars? Does the most popular station belong to that postal code?
# Overall?
Autolib[(Autolib.Bluecar_counter_difference < 0)].groupby('Postal_code')['Postal_code'].count().sort_values(ascending = False).head(10)

Postal_code
75015    290176
75016    238231
75017    229258
75013    219008
75008    214190
75014    199524
75012    197040
75019    185609
75020    179884
75018    170006
Name: Postal_code, dtype: int64

In [0]:
# Bonus Question 3.2
# What postal code is the most popular for picking up Bluecars? Does the most popular station belong to that postal code?
# At the most popular picking hour?
Autolib[(Autolib.Bluecar_counter_difference < 0) & (Autolib.hour == 4)].groupby('Postal_code')['Postal_code'].count().sort_values(ascending = False).head(10)

Postal_code
75016    11849
75015    11484
75008    10333
75013     9735
75017     9491
75014     8653
75012     8487
75007     7614
75011     7191
75019     7026
Name: Postal_code, dtype: int64

Bonus Question 4

Do the results change if you consider Utilib and Utilib 1.4 instead of Bluecars?

Questions Relating to Utilib Counter

In [0]:
# Research Question
# Identify the most popular hour of the day for picking up a Utilib in the city of Paris 
# over the month of April 2018

Autolib[(Autolib.City == 'Paris') & (Autolib.Utilib_counter_difference < 0)].groupby('hour')['hour'].count().sort_values(ascending = False).head(10)

hour
5     19827
7     19555
8     19217
4     19134
3     19107
2     18982
6     18948
10    18457
21    18088
9     17964
Name: hour, dtype: int64

In [0]:
# Bonus Question 1
# What is the most popular hour for returning cars?

Autolib[Autolib.Utilib_counter_difference > 0].groupby('hour')['hour'].count().sort_values(ascending = False).head(10)

hour
5     38484
6     38450
7     38141
4     38101
3     37932
2     37686
8     36719
9     35289
10    35123
21    34080
Name: hour, dtype: int64

In [0]:
# Bonus Question 2
# What station is the most popular?
# At the most popular picking hour?
Autolib[(Autolib.Kind == 'STATION') & (Autolib.Status == 'ok') & (Autolib.hour == 5)].groupby('Public_name')['Public_name'].count().sort_values(ascending= False).head(10)

Public_name
Paris Commerce 5                       555
Villejuif Ãpi d'Or 2                  554
Paris Mozart 2                         552
Antony Velpeau 14                      552
Paris MÃ©nilmontant 30                 552
Paris Saint Placide 58                 552
Le Chesnay Pottier 7                   552
Paris Porte de Villiers 28             552
Paris Victor Hugo 180                  552
Champigny-sur-Marne Bois l'AbbÃ© 53    552
Name: Public_name, dtype: int64

In [0]:
# Bonus Question 3.1
# What postal code is the most popular for picking up Utilib? Does the most popular station belong to that postal code?
# Overall?
Autolib[(Autolib.Utilib_counter_difference < 0)].groupby('Postal_code')['Postal_code'].count().sort_values(ascending = False).head(10)

Postal_code
75015    45486
75016    33698
75017    33043
92000    31549
75020    30997
75019    28455
75012    23935
75013    23558
75018    23143
75008    22928
Name: Postal_code, dtype: int64

In [0]:
# Bonus Question 3.2
# What postal code is the most popular for picking up Utilib? Does the most popular station belong to that postal code?
# At the most popular picking hour?
Autolib[(Autolib.Utilib_counter_difference < 0) & (Autolib.hour == 5)].groupby('Postal_code')['Postal_code'].count().sort_values(ascending = False).head(10)

Postal_code
75015    2204
75019    1708
92000    1671
75020    1449
75016    1365
75017    1252
75010    1162
75012    1116
92130    1067
75014    1064
Name: Postal_code, dtype: int64

Questions Relating to Utilib 1.4 Counter

In [0]:
# Research Question
# Identify the most popular hour of the day for picking up a Utilib 1.4 in the city of Paris 
# over the month of April 2018

Autolib[(Autolib.City == 'Paris') & (Autolib['Utilib1.4_counter_difference'] < 0)].groupby('hour')['hour'].count().sort_values(ascending = False).head(10)

hour
6     36654
5     36168
7     35595
10    35230
4     35145
8     35064
11    34833
9     34797
3     34568
2     34256
Name: hour, dtype: int64

In [0]:
# Bonus Question 1
# What is the most popular hour for returning cars?

Autolib[Autolib['Utilib1.4_counter_difference'] > 0].groupby('hour')['hour'].count().sort_values(ascending = False).head(10)

hour
5     71316
4     71133
3     70851
6     70525
2     69718
7     68545
8     65717
9     64000
10    63809
11    62913
Name: hour, dtype: int64

In [0]:
# Bonus Question 2
# What station is the most popular?
# At the most popular picking hour?
Autolib[(Autolib.Kind == 'STATION') & (Autolib.Status == 'ok') & (Autolib.hour == 6)].groupby('Public_name')['Public_name'].count().sort_values(ascending= False).head(10)

Public_name
Paris Volta 39                                   553
Paris Bourdonnais 45                             553
Gennevilliers Vieux Chemin de Saint-Denis 106    553
Paris Tolbiac 245                                552
Paris Paix 24                                    551
Paris Mozart 68                                  551
Paris Sorbier 14                                 551
Pantin Cartier Bresson 84                        551
Boulogne-Billancourt Abel Gance 6                551
Paris Voltaire 182                               551
Name: Public_name, dtype: int64

In [0]:
# Bonus Question 3.1
# What postal code is the most popular for picking up Utilib 1.4? Does the most popular station belong to that postal code?
# Overall?
Autolib[(Autolib['Utilib1.4_counter_difference'] < 0)].groupby('Postal_code')['Postal_code'].count().sort_values(ascending = False).head(10)

Postal_code
75015    73837
75016    69140
75017    55398
75013    52331
75020    50941
92000    50582
75019    48143
75014    46498
75018    45770
75012    43715
Name: Postal_code, dtype: int64

In [0]:
# Bonus Question 3.2
# What postal code is the most popular for picking up Utilib 1.4? Does the most popular station belong to that postal code?
# At the most popular picking hour?
Autolib[(Autolib['Utilib1.4_counter_difference'] < 0) & (Autolib.hour == 6)].groupby('Postal_code')['Postal_code'].count().sort_values(ascending = False).head(10)

Postal_code
75015    3484
75016    3394
75017    3001
75014    2321
92000    2316
75018    2249
75020    2212
75013    2157
75019    2065
75008    1878
Name: Postal_code, dtype: int64